heat_template_version: 2015-10-15
description: template to create a server instance with an attached volume

parameters:
  server_image:
    type: string
    label: Image name or ID
    description: Image to be used for compute instance
  server_flavor:
    type: string
    label: Flavor
    description: Type of flavor to be used
  server_key:
    type: string
    label: Key name
    description: Name of key-pair to be used for compute instance
  server_network:
    type: string
    label: Private network name or ID
    description: Network to attach instance to.
  volume_size:
    type: string
    label: size of volume
    description: This is the size of the Volume

resources:
  server:
    type: OS::Nova::Server
    properties:
      image: { get_param: server_image }
      flavor: { get_param: server_flavor }
      key_name: { get_param: server_key }
      networks:
        - network: { get_param: server_network }
      user_data_format: RAW
      user_data: |
        #!/bin/bash
        mkfs.ext4 /dev/vdb
        echo '/dev/vdb /mnt ext4 defaults 1 1' >> /etc/fstab
        mount -a

  volume:
   type: OS::Cinder::Volume
   properties:
      size: { get_param: volume_size }

  volume_attachment:
   type: OS::Cinder::VolumeAttachment
   properties:
      instance_uuid: { get_resource: server }
      volume_id: { get_resource: volume }
      mountpoint: /dev/vdb

outputs:
 server_name:
   description: Name of the server instance
   value: { get_attr: [server, name] }
 server_address:
   description: IP address of the server instance
   value: { get_attr: [server, first_address] }
 volume_name:
   description: Volume name attached to the server instance
   value: { get_attr: [volume, display_name] }
 volume_type:
   description: Volume type attached to the server instance
   value: { get_attr: [volume, volume_type] }


