heat_template_version: 2015-10-15
description: Simple template to deploy a compute instance

resources:
  my_instance:
    type: OS::Nova::Server
    properties:
      image: cirros
      flavor: small
      key_name: demokey
      networks:
        - network: tenant-network
